### ISSUE TITLE
CI test errors on BIg Endian systems

### ISSUE THREAD

**Issue by olebole** [cgohlke/tifffile#18]
Hi,

I am maintaining the [Debian package of tifffile](https://tracker.debian.org/pkg/tifffile), which is also used in Ubuntu. The Ubuntu distribution runs the CI tests on all their supported platforms, and found a regression on the s390x platform, which is a 64 bit big endian one:
```
=================================== FAILURES ===================================
____________________________ test_issue_valueoffset ____________________________

    def test_issue_valueoffset():
        """Test read TiffTag.valueoffsets."""
        unpack = struct.unpack
        data = random_data('uint16', (2, 19, 31))
        software = 'test_tifffile'
        with TempFileName('valueoffset') as fname:
            imwrite(fname, data, software=software, photometric='minisblack')
            with TiffFile(fname, _useframes=True) as tif:
                with open(fname, 'rb') as fh:
                    page = tif.pages[0]
                    # inline value
                    fh.seek(page.tags['ImageLength'].valueoffset)
>                   assert page.imagelength == unpack('H', fh.read(2))[0]
E                   assert 19 == 0
E                     -19
E                     +0

test_tifffile.py:638: AssertionError
____________________________ test_func_memmap_fail _____________________________

    def test_func_memmap_fail():
        """Test non-native byteorder can not be memory mapped."""
        with TempFileName('memmap_fail') as fname:
            with pytest.raises(ValueError):
>               memmap(fname, shape=(16, 16), dtype='float32', byteorder='>')
E               Failed: DID NOT RAISE <class 'ValueError'>

test_tifffile.py:1000: Failed
_________________________ test_func_byteorder_isnative _________________________

    def test_func_byteorder_isnative():
        """Test byteorder_isnative function."""
>       assert not byteorder_isnative('>')
E       AssertionError: assert not True
E        +  where True = byteorder_isnative('>')

test_tifffile.py:1018: AssertionError
_____________________________ test_func_unpack_rgb _____________________________

    def test_func_unpack_rgb():
        """Test unpack_rgb function."""
        data = struct.pack('BBBB', 0x21, 0x08, 0xFF, 0xFF)
>       assert_array_equal(unpack_rgb(data, '<B', (5, 6, 5), False),
                           [1, 1, 1, 31, 63, 31])
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatch: 50%
E       Max absolute difference: 7
E       Max relative difference: 7.
E        x: array([ 4,  8,  8, 31, 63, 31], dtype=uint8)
E        y: array([ 1,  1,  1, 31, 63, 31])

test_tifffile.py:1185: AssertionError
======= 4 failed, 1609 passed, 268 skipped, 30 xfailed in 35.44 seconds ========
```
The test was done with version 2020.06.03, 2020.05.11 was (probably) working.
Full test log [here](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/s390x/t/tifffile/20200612_195249_ec5f1@/log.gz).

**Comment by cgohlke** [comment]
Should be fixed in v2020.7.17.

**Comment by bryceharrington** [comment]
Hi cgohike,

Thanks for the fixes, and it looks like this mostly addressed the issues seen in Ubuntu's CI for s390x, however we're still seeing the first test case failing:

=================================== FAILURES ===================================
____________________________ test_issue_valueoffset ____________________________

    def test_issue_valueoffset():
        """Test read TiffTag.valueoffsets."""
        unpack = struct.unpack
        data = random_data('uint16', (2, 19, 31))
        software = 'test_tifffile'
        with TempFileName('valueoffset') as fname:
            imwrite(fname, data, software=software, photometric='minisblack')
            with TiffFile(fname, _useframes=True) as tif:
                with open(fname, 'rb') as fh:
                    page = tif.pages[0]
                    # inline value
                    fh.seek(page.tags['ImageLength'].valueoffset)
>                   assert (
                        page.imagelength
                        == unpack(tif.byteorder + 'H', fh.read(2))[0]
                    )
E                   assert 19 == 0
E                     -19
E                     +0

test_tifffile.py:726: AssertionError

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-hirsute/hirsute/s390x/t/tifffile/20201208_005433_a12c1@/log.gz

From the above bug report it sounds like this was the change that should have fixed the issue:

https://github.com/cgohlke/tifffile/commit/65ca673b6daf73ca05131e1cd790c6b7578fe133

**Comment by cgohlke** [comment]
Thanks for following up. Hopefully that's fixed in v2020.12.8.
